server:
  port: 18081

mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml  # 读取映射文件
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增 id策略
feign:
  sentinel:
    enabled: true
spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: gmall-tx-group
  rabbitmq:
    host: 192.168.242.128
    virtual-host: /tobeey
    username: tobeey
    password: 123456
    publisher-confirm-type: correlated
    publisher-returns: true